# Generated by Django 2.1.7 on 2019-03-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190312_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-date',)},
        ),
    ]
