# Generated by Django 2.1.7 on 2019-03-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190309_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('view_count', 'name')},
        ),
    ]
