# Generated by Django 2.1.7 on 2019-03-10 11:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190309_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
