# Generated by Django 2.1.7 on 2019-03-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-view_count', 'name')},
        ),
    ]
