# Generated by Django 2.1.7 on 2019-03-27 07:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_basket_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='specifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=None),
        ),
    ]
