# Generated by Django 2.1.7 on 2019-03-27 07:49

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_category_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='specifications',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
