# Generated by Django 2.1.7 on 2019-03-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_category_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
