# Generated by Django 2.1.7 on 2019-04-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190401_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'RECIEVED'), (1, 'PROCCESSED'), (2, 'DELIVERED'), (3, 'REJECTED')], default=0),
        ),
    ]
