# Generated by Django 2.1.7 on 2019-04-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190402_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default='2000-01-01 00:00'),
        ),
    ]
