# Generated by Django 2.1.7 on 2019-04-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_product_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-rating', 'name')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
    ]
