# Generated by Django 2.1.7 on 2019-05-17 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertising_costs', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_user_count', models.PositiveIntegerField(default=0)),
                ('new_user_count', models.PositiveIntegerField(default=0)),
                ('used_coupone_count', models.PositiveIntegerField(default=0)),
                ('average_discount_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
