# Generated by Django 2.1.7 on 2019-05-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasample',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
