# Generated by Django 2.1.7 on 2019-05-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_datasample_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasample',
            old_name='average_discount_count',
            new_name='average_discount',
        ),
    ]
