# Generated by Django 2.1.7 on 2019-05-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20190517_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasample',
            name='orders_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
