# Generated by Django 2.1.7 on 2019-03-07 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190307_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='basket',
            field=models.OneToOneField(default=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
