# Generated by Django 2.1.7 on 2019-03-07 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='basket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
