# Generated by Django 2.1.7 on 2019-03-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190307_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='basket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Basket'),
        ),
    ]
